version: '3'
services:
  mysql:
    image: mysql:8.1
    restart: always
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: passowrd
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./data/mysql/:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d